2020-03-19 16:00:28,703 ERROR: Exception on /index [GET] [in c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\JHN\Desktop\Online_Calendar\app\routes.py", line 39, in index
    prev_url=prev_url)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\index.html", line 11, in block "app_content"
    {% include '_event.html' %}
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\_event.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2020-03-19 16:01:30,579 INFO: Microblog startup [in C:\Users\JHN\Desktop\Online_Calendar\app\__init__.py:47]
2020-03-19 16:14:43,051 INFO: Microblog startup [in C:\Users\JHN\Desktop\Online_Calendar\app\__init__.py:49]
2020-03-19 16:14:49,500 ERROR: Exception on /index [GET] [in c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\JHN\Desktop\Online_Calendar\app\routes.py", line 39, in index
    prev_url=prev_url)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\base.html", line 54, in template
    {% endblock %}
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\JHN\Desktop\Online_Calendar\app\templates\base.html", line 54, in template
    {% endblock %}
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\users\jhn\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-03-19 16:16:20,235 INFO: Microblog startup [in C:\Users\JHN\Desktop\Online_Calendar\app\__init__.py:49]
2020-03-19 16:22:20,782 INFO: Microblog startup [in C:\Users\JHN\Desktop\Online_Calendar\app\__init__.py:49]
2020-03-19 16:23:38,603 INFO: Microblog startup [in C:\Users\JHN\Desktop\Online_Calendar\app\__init__.py:49]
